export {
  animate,
  makeAnimated,
  AnimateValue,
  isAnimateValue,
  Easing,
  combine,
  to,
  withSpring,
  withTiming,
  withDecay,
  withDelay,
  withSequence,
  withLoop,
  withStagger,
  useValue,
  Presence,
  PresenceContext,
  usePresence,
  useIsPresent,
  recipes,
  fadeIn,
  fadeOut,
  fadeInUp,
  fadeInDown,
  fadeInLeft,
  fadeInRight,
  slideInUp,
  slideInDown,
  slideInLeft,
  slideInRight,
  slideOutUp,
  slideOutDown,
  slideOutLeft,
  slideOutRight,
  scaleIn,
  scaleOut,
  scaleUp,
  scaleDown,
  bounceIn,
  bounceOut,
  rotateIn,
  rotateOut,
  spin,
  zoomIn,
  zoomOut,
  flipX,
  flipY,
  slideFadeIn,
  slideFadeOut,
  scaleFadeIn,
  scaleFadeOut,
  hoverScale,
  hoverLift,
  hoverGlow,
  pressScale,
  pressDown,
  exitFade,
  exitSlideUp,
  exitSlideDown,
  exitScale,
} from './animation';

export type {
  Primitive,
  ExtrapolateConfig,
  ExtrapolateType,
  Callbacks,
  SpringOptions,
  TimingOptions,
  DecayOptions,
  SequenceOptions,
  DelayOptions,
  LoopOptions,
  StaggerOptions,
  Descriptor,
  Controls,
  AnimateProp,
  AnimateStyle,
  AnimateAttributes,
  AnimateHTMLAttributes,
  AnimateSVGAttributes,
  LayoutOptions,
  PresenceProps,
  PresenceContextValue,
} from './animation';

export { useOutsideClick } from './hooks/events/useOutsideClick';
export { useInView, type UseInViewOptions } from './hooks/observers/useInView';

export {
  useScrollProgress,
  type UseScrollProgressOptions,
} from './gestures/hooks/useScrollProgress';

export { Gesture } from './gestures/api/Gesture';
export { useGesture } from './gestures/hooks/useGesture';
export { GesturePhase } from './gestures/engine/phases';
export type {
  GestureType,
  GestureHandlers,
  BaseGestureConfig,
  GestureDescriptor,
  PanEvent,
  MoveEvent,
  WheelEvent,
  ScrollEvent,
  SwipeEvent,
  SwipeGestureConfig,
  SwipeHandlers,
  HoverEvent,
} from './gestures/api/Gesture';

export { clamp, rubberClamp, snapTo, move } from './utils';
